import { useState } from "react";
import { motion } from "framer-motion";
import { FileText, Plus, ExternalLink, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

interface Doc {
  id: string;
  title: string;
  url: string;
  agent: string;
  createdAt: string;
  category: string;
}

const STORAGE_KEY = "atlas-docs";

const defaultDocs: Doc[] = [
  { id: "1", title: "Q1 Campaign Strategy", url: "https://docs.google.com", agent: "Business Executive", createdAt: "Mar 5, 2026", category: "Strategy" },
  { id: "2", title: "Testosterone Optimization Research", url: "https://docs.google.com", agent: "Personal Assistant", createdAt: "Mar 4, 2026", category: "Research" },
  { id: "3", title: "Client Onboarding Sequence Draft", url: "https://docs.google.com", agent: "Business Executive", createdAt: "Mar 3, 2026", category: "Email" },
  { id: "4", title: "YouTube Script — Supplement Review", url: "https://docs.google.com", agent: "Business Executive", createdAt: "Mar 2, 2026", category: "Content" },
  { id: "5", title: "Competitor Ad Analysis Report", url: "https://docs.google.com", agent: "Business Executive", createdAt: "Mar 1, 2026", category: "Research" },
  { id: "6", title: "Weekly Health Metrics Summary", url: "https://docs.google.com", agent: "Personal Assistant", createdAt: "Feb 28, 2026", category: "Health" },
];

function loadDocs(): Doc[] {
  try {
    const stored = localStorage.getItem(STORAGE_KEY);
    if (stored) return JSON.parse(stored);
  } catch {}
  return defaultDocs;
}

const categoryColors: Record<string, string> = {
  Strategy: "border-primary/30 text-primary",
  Research: "border-atlas-warning/30 text-atlas-warning",
  Email: "border-atlas-cyan/30 text-[hsl(var(--atlas-cyan))]",
  Content: "border-atlas-success/30 text-atlas-success",
  Health: "border-purple-500/30 text-purple-400",
};

const container = { hidden: {}, show: { transition: { staggerChildren: 0.04 } } };
const item = { hidden: { opacity: 0, y: 8 }, show: { opacity: 1, y: 0 } };

export default function DocsPage() {
  const [docs, setDocs] = useState<Doc[]>(loadDocs);
  const [addOpen, setAddOpen] = useState(false);
  const [newDoc, setNewDoc] = useState({ title: "", url: "", agent: "", category: "" });

  const save = (updated: Doc[]) => {
    setDocs(updated);
    localStorage.setItem(STORAGE_KEY, JSON.stringify(updated));
  };

  const addDoc = () => {
    if (!newDoc.title.trim() || !newDoc.url.trim()) return;
    save([{ ...newDoc, id: crypto.randomUUID(), createdAt: new Date().toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" }) }, ...docs]);
    setNewDoc({ title: "", url: "", agent: "", category: "" });
    setAddOpen(false);
  };

  const deleteDoc = (id: string) => save(docs.filter((d) => d.id !== id));

  return (
    <motion.div variants={container} initial="hidden" animate="show" className="space-y-6 max-w-4xl">
      <motion.div variants={item} className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-foreground">Docs</h1>
          <p className="text-sm text-muted-foreground mt-1">Google Docs generated by Atlas agents</p>
        </div>
        <Button size="sm" className="gap-2" onClick={() => setAddOpen(true)}>
          <Plus className="h-4 w-4" /> Add Doc
        </Button>
      </motion.div>

      <motion.div variants={item} className="space-y-2">
        {docs.map((doc) => (
          <motion.div
            key={doc.id}
            variants={item}
            className="glass-card p-4 flex items-center gap-4 hover:border-primary/30 transition-colors group"
          >
            <div className="h-9 w-9 rounded-lg bg-primary/10 flex items-center justify-center shrink-0">
              <FileText className="h-4 w-4 text-primary" />
            </div>
            <div className="flex-1 min-w-0">
              <div className="text-sm font-medium text-foreground truncate">{doc.title}</div>
              <div className="flex items-center gap-2 mt-1">
                <span className="text-[11px] text-muted-foreground">{doc.agent}</span>
                <span className="text-[11px] text-muted-foreground">•</span>
                <span className="text-[11px] text-muted-foreground">{doc.createdAt}</span>
              </div>
            </div>
            <Badge variant="outline" className={`text-[10px] ${categoryColors[doc.category] || "text-muted-foreground border-muted-foreground/30"}`}>
              {doc.category}
            </Badge>
            <a
              href={doc.url}
              target="_blank"
              rel="noopener noreferrer"
              className="text-muted-foreground hover:text-primary transition-colors"
            >
              <ExternalLink className="h-4 w-4" />
            </a>
            <button
              onClick={() => deleteDoc(doc.id)}
              className="text-muted-foreground hover:text-destructive transition-colors opacity-0 group-hover:opacity-100"
            >
              <Trash2 className="h-4 w-4" />
            </button>
          </motion.div>
        ))}
      </motion.div>

      <Dialog open={addOpen} onOpenChange={setAddOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Add Document</DialogTitle>
          </DialogHeader>
          <div className="space-y-4">
            <div className="space-y-2">
              <Label>Title</Label>
              <Input value={newDoc.title} onChange={(e) => setNewDoc({ ...newDoc, title: e.target.value })} placeholder="Document title" />
            </div>
            <div className="space-y-2">
              <Label>Google Docs URL</Label>
              <Input value={newDoc.url} onChange={(e) => setNewDoc({ ...newDoc, url: e.target.value })} placeholder="https://docs.google.com/..." />
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label>Agent</Label>
                <Input value={newDoc.agent} onChange={(e) => setNewDoc({ ...newDoc, agent: e.target.value })} placeholder="Which agent created it" />
              </div>
              <div className="space-y-2">
                <Label>Category</Label>
                <Input value={newDoc.category} onChange={(e) => setNewDoc({ ...newDoc, category: e.target.value })} placeholder="e.g. Research, Strategy" />
              </div>
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setAddOpen(false)}>Cancel</Button>
            <Button onClick={addDoc}>Add</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </motion.div>
  );
}
